name: Circular Dependency Test
on: [push]

jobs:
  job-a:
    runs-on: ubuntu-latest
    needs: job-b
    steps:
      - name: Job A
        run: echo "This should not run due to circular dependency"

  job-b:
    runs-on: ubuntu-latest
    needs: job-a
    steps:
      - name: Job B
        run: echo "This should not run due to circular dependency"
