name: Container Test
on: push

jobs:
  container-test:
    runs-on: ubuntu-latest
    steps:
      - name: Test container execution
        run: |
          echo "Running in container!"
          whoami
          pwd
          ls -la
          
      - name: Check system info
        run: |
          echo "Container OS info:"
          cat /etc/os-release | head -5
          echo "Available packages:"
          which apt-get docker git || echo "Some tools not available"
          
      - name: Test file operations
        run: |
          echo "Creating test file in container"
          echo "Hello from container" > container-test.txt
          cat container-test.txt
          ls -la container-test.txt
