name: Parallel Execution Test
on: [push]

jobs:
  independent-1:
    runs-on: ubuntu-latest
    steps:
      - name: Task 1
        run: |
          echo "Independent task 1 starting at $(date)"
          sleep 3
          echo "Independent task 1 completed at $(date)"

  independent-2:
    runs-on: ubuntu-latest
    steps:
      - name: Task 2
        run: |
          echo "Independent task 2 starting at $(date)"
          sleep 2
          echo "Independent task 2 completed at $(date)"

  independent-3:
    runs-on: ubuntu-latest
    steps:
      - name: Task 3
        run: |
          echo "Independent task 3 starting at $(date)"
          sleep 1
          echo "Independent task 3 completed at $(date)"

  dependent-task:
    runs-on: ubuntu-latest
    needs: [independent-1, independent-2, independent-3]
    steps:
      - name: Final task
        run: |
          echo "Final task starting at $(date)"
          echo "All independent tasks have completed"
          echo "Final task completed at $(date)"
