name: Test Environment Variables

on: [push]

jobs:
  test-env:
    runs-on: ubuntu-latest
    steps:
      - name: Show environment variables
        run: |
          echo "GITHUB_TOKEN is $([ -n "$GITHUB_TOKEN" ] && echo "set" || echo "not set")"
          echo "CI: $CI"
          echo "VERMONT_RUNNER: $VERMONT_RUNNER" 
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
