name: Test Checkout Action

on: [push]

jobs:
  test-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: List files after checkout
        run: ls -la
